# Generated by Django 2.1.4 on 2019-01-01 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='管理员名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='邮箱')),
                ('phone', models.IntegerField(unique=True, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('name', models.CharField(max_length=20, verbose_name='相册名')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('subject', models.CharField(max_length=20, verbose_name='主题')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=10, verbose_name='类别名')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('identifier', models.CharField(max_length=200, verbose_name='序列号')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('organizer', models.IntegerField(verbose_name='发起人')),
                ('subject', models.CharField(max_length=20, verbose_name='主题')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('vote', models.IntegerField(default=0, verbose_name='投票数')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('author', models.CharField(max_length=15, verbose_name='作者')),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=15, verbose_name='标题')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('path', models.CharField(max_length=100, verbose_name='路径')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Album', verbose_name='相册id')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='植物名')),
                ('address', models.CharField(max_length=20, verbose_name='植物产地')),
            ],
        ),
        migrations.CreateModel(
            name='PlantToCategory',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Category', verbose_name='类别id')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant', verbose_name='植物id')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='邮箱')),
                ('phone', models.IntegerField(unique=True, verbose_name='手机号')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='judge',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant', verbose_name='植物id'),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant', verbose_name='植物id'),
        ),
        migrations.AddField(
            model_name='album',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant', verbose_name='植物id'),
        ),
    ]
