# Generated by Django 2.1.4 on 2019-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='plant',
            name='avatar',
            field=models.CharField(default='', max_length=100, verbose_name='植物头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
