# Generated by Django 2.2 on 2019-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='title',
        ),
        migrations.AddField(
            model_name='rank',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='排行榜'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
