# Generated by Django 2.1.4 on 2018-12-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('organizer', models.IntegerField(max_length=11)),
                ('subject', models.CharField(max_length=20)),
                ('star', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('path', models.CharField(max_length=100)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlantToCategory',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Category')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='plant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='judge',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant'),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant'),
        ),
        migrations.AddField(
            model_name='album',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant'),
        ),
    ]
