# Generated by Django 2.1.4 on 2019-04-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190407_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planttocategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='planttocategory',
            name='plant_id',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '植物类别', 'verbose_name_plural': '植物类别'},
        ),
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Category', verbose_name='植物类别id'),
        ),
        migrations.DeleteModel(
            name='PlantToCategory',
        ),
    ]
