# Generated by Django 2.1.4 on 2019-04-07 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190407_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('subject', models.CharField(max_length=20, verbose_name='主题')),
                ('title', models.TextField(default='', verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '排行榜',
                'verbose_name_plural': '排行榜',
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='id')),
                ('vote_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票时间')),
                ('comment', models.TextField(default='', verbose_name='评论')),
                ('vote', models.IntegerField(default=0, verbose_name='投票数')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'db_table': 'vote',
            },
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='plant_id',
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Gallery', verbose_name='相册'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to='', verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='植物头像'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Category', verbose_name='植物类别'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.AddField(
            model_name='vote',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Plant', verbose_name='植物'),
        ),
        migrations.AddField(
            model_name='vote',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Rank', verbose_name='排行榜'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='用户'),
        ),
    ]
