# Generated by Django 2.1.4 on 2018-12-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181231_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
